In [2]:
import numpy as np

In [3]:
test = np.array([[1,1,1,1,1], [2,2,2,2,2]])

In [4]:
train = np.array([[10,10,10,10,10],[20,20,20,20,20], [30,30,30,30,30]])

In [59]:
test1

array([1, 2, 3, 4, 5])

In [60]:
test2

array([[10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20]])

In [61]:
np.abs(test - train).sum(axis=1)

array([35, 85])

In [49]:
def compute_distances_one_loop(X_train, X_test):

    num_train = X_train.shape[0]
    num_test = X_test.shape[0]
    dists = np.zeros((num_test, num_train), np.float32)
    for i_test in range(num_test):
        # TODO: Fill the whole row of dists[i_test]
        # without additional loops or list comprehensions
        dists[i_test] = np.abs(X_test[i_test, :] - X_train).sum(axis=1)
    return dists

In [50]:
compute_distances_one_loop(train, test)

ValueError: could not broadcast input array from shape (2,5) into shape (2)

In [42]:
test.shape

(1, 5)

In [43]:
train.shape

(2, 5)

In [62]:
def compute_distances_no_loop(X_train, X_test):

    num_train = X_train.shape[0]
    num_test = X_test.shape[0]
    dists = np.zeros((num_test, num_train), np.float32)
    
    dist = np.abs(X_test[:, np.newaxis] - X_train).sum(axis=2)
    
    return dists

In [75]:
test

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [5]:
train

array([[10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30]])

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
test[:, np.newaxis] - train

array([[[ -9,  -9,  -9,  -9,  -9],
        [-19, -19, -19, -19, -19],
        [-29, -29, -29, -29, -29]],

       [[ -8,  -8,  -8,  -8,  -8],
        [-18, -18, -18, -18, -18],
        [-28, -28, -28, -28, -28]]])

In [10]:
x = np.array([10,20,30,40,50,60])

In [11]:
x[[0,1,2,3]]

array([10, 20, 30, 40])

In [12]:
import random

In [17]:
x = [1,2,3,4,5]

In [18]:
q = random.shuffle(x)

In [19]:
x

[2, 4, 5, 1, 3]

In [37]:
x = np.array([[1,2,3,4,5], [10,20,30,40,50], [2,3,4,5,6]])

In [38]:
x

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [ 2,  3,  4,  5,  6]])

In [39]:
y = np.array([1,2,3])

In [40]:
y

array([1, 2, 3])

In [42]:
z = np.append(x, y[:, np.newaxis], axis=1)

In [46]:
z[:, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [ 2,  3,  4,  5,  6]])

In [54]:
a = np.array(np.array() for i in range(5))