In [3]:
test = np.array([[1,1,1,1,1], [2,2,2,2,2]])

In [4]:
train = np.array([[10,10,10,10,10],[20,20,20,20,20], [30,30,30,30,30]])

In [59]:
test1

array([1, 2, 3, 4, 5])

In [60]:
test2

array([[10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20]])

In [61]:
np.abs(test - train).sum(axis=1)

array([35, 85])

In [49]:
def compute_distances_one_loop(X_train, X_test):

    num_train = X_train.shape[0]
    num_test = X_test.shape[0]
    dists = np.zeros((num_test, num_train), np.float32)
    for i_test in range(num_test):
        # TODO: Fill the whole row of dists[i_test]
        # without additional loops or list comprehensions
        dists[i_test] = np.abs(X_test[i_test, :] - X_train).sum(axis=1)
    return dists

In [50]:
compute_distances_one_loop(train, test)

ValueError: could not broadcast input array from shape (2,5) into shape (2)

In [42]:
test.shape

(1, 5)

In [43]:
train.shape

(2, 5)

In [62]:
def compute_distances_no_loop(X_train, X_test):

    num_train = X_train.shape[0]
    num_test = X_test.shape[0]
    dists = np.zeros((num_test, num_train), np.float32)
    
    dist = np.abs(X_test[:, np.newaxis] - X_train).sum(axis=2)
    
    return dists

In [75]:
test

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [5]:
train

array([[10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30]])

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [78]:
test[:, np.newaxis] - train

array([[[ -9,  -9,  -9,  -9,  -9],
        [-19, -19, -19, -19, -19],
        [-29, -29, -29, -29, -29]],

       [[ -8,  -8,  -8,  -8,  -8],
        [-18, -18, -18, -18, -18],
        [-28, -28, -28, -28, -28]]])

In [10]:
x = np.array([10,20,30,40,50,60])

In [11]:
x[[0,1,2,3]]

array([10, 20, 30, 40])

In [12]:
import random

In [17]:
x = [1,2,3,4,5]

In [18]:
q = random.shuffle(x)

In [19]:
x

[2, 4, 5, 1, 3]

In [37]:
x = np.array([[1,2,3,4,5], [10,20,30,40,50], [2,3,4,5,6]])

In [38]:
x

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [ 2,  3,  4,  5,  6]])

In [39]:
y = np.array([1,2,3])

In [40]:
y

array([1, 2, 3])

In [42]:
z = np.append(x, y[:, np.newaxis], axis=1)

In [46]:
z[:, :-1]

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50],
       [ 2,  3,  4,  5,  6]])

In [54]:
a = np.array(np.array() for i in range(5))

In [14]:
a = np.array([[],[],[],[],[]])

In [17]:
a

array([], shape=(5, 0), dtype=float64)

In [18]:
a[0]

array([], dtype=float64)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [20]:
from dataset import load_svhn
from knn import KNN
from metrics import binary_classification_metrics, multiclass_accuracy

In [21]:
train_X, train_y, test_X, test_y = load_svhn("data", max_train=1000, max_test=100)

In [22]:
binary_train_mask = (train_y == 0) | (train_y == 9)
binary_train_X = train_X[binary_train_mask]
binary_train_y = train_y[binary_train_mask] == 0

binary_test_mask = (test_y == 0) | (test_y == 9)
binary_test_X = test_X[binary_test_mask]
binary_test_y = test_y[binary_test_mask] == 0

# Reshape to 1-dimensional array [num_samples, 32*32*3]
binary_train_X = binary_train_X.reshape(binary_train_X.shape[0], -1)
binary_test_X = binary_test_X.reshape(binary_test_X.shape[0], -1)

In [23]:
X = binary_train_X.copy()
y = binary_train_y.copy()

In [29]:
type(X)

numpy.ndarray

In [43]:
train_folds_X = np.array([[] for _ in range(5)])
train_folds_y =np.array([[] for _ in range(5)])

In [44]:
train_folds_X

array([], shape=(5, 0), dtype=float64)

In [45]:
all_shuffled = X

In [46]:
all_shuffled = np.append(X, y[:, np.newaxis], axis=1)

In [47]:
np.random.shuffle(all_shuffled)

In [48]:
all_shuffled

array([[ 94.,  72.,  81., ..., 154., 162.,   0.],
       [ 91., 103., 120., ..., 122., 123.,   1.],
       [134., 143., 149., ..., 164., 165.,   1.],
       ...,
       [ 61.,  91.,  81., ..., 115., 103.,   1.],
       [ 18.,  18.,  52., ...,   8.,  49.,   1.],
       [162., 163., 181., ..., 222., 225.,   1.]], dtype=float32)

In [50]:
train_folds_X[20 % 5].append([1,2,3,4,5,6])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [57]:
train_folds_X[20 % 5] = np.vstack((train_folds_X[20 % 5], [1,2,3,4,5]))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [58]:
train_folds_X[20 % 5]

array([], dtype=float64)

In [70]:
all_shuffled.shape

(121, 3073)

In [61]:
all_shuffled[1]

array([ 94.,  72.,  81., ..., 154., 162.,   0.], dtype=float32)

In [71]:
train_folds_X = np.array((5, 3073))

In [72]:
train_folds_X

array([   5, 3073])

In [88]:
num_folds = 5
train_folds_X = []
train_folds_y = []

# TODO: split the training data in 5 folds and store them in train_folds_X/train_folds_y
for i in range(num_folds):
    train_folds_X.append(binary_train_X[np.arange(i, binary_train_X.shape[0], num_folds)])
    train_folds_y.append(binary_train_y[np.arange(i, binary_train_y.shape[0], num_folds)])

In [78]:
np.arange(5, binary_train_X.shape[0], 5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120])

In [79]:
range(5, binary_train_X.shape[0], 5)

range(5, 121, 5)

In [80]:
train_folds_X = []

In [81]:
 train_folds_X.append(binary_train_X[range(5, binary_train_X.shape[0], 5)])

In [95]:
all_shuffled = np.append(binary_train_X, binary_train_y[:, np.newaxis], axis=1)

In [92]:
train_folds_y.astype(int)

AttributeError: 'list' object has no attribute 'astype'

In [99]:
all_shuffled[range(i, all_shuffled.shape[0], num_folds)][:, -1].astype(bool)

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True])

In [101]:
a = np.array([])

In [105]:
f1_folds = np.zeros(num_folds)

In [106]:
f1_folds

array([0., 0., 0., 0., 0.])

In [107]:
folds_f1 = np.zeros((num_folds,), float)

In [108]:
folds_f1

array([0., 0., 0., 0., 0.])

In [109]:
train_folds_X

[array([[216., 227., 231., ..., 116.,  79.,  83.],
        [120., 119., 121., ..., 119., 118., 124.],
        [133., 163., 137., ..., 136., 166., 142.],
        ...,
        [112., 108., 115., ...,  78.,  66.,  79.],
        [157., 161., 173., ..., 138., 130., 128.],
        [142., 178., 214., ..., 132., 150., 170.]], dtype=float32),
 array([[ 98.,  86., 101., ...,  51.,  42.,  47.],
        [193., 191., 196., ..., 189., 186., 191.],
        [146., 156., 148., ..., 130., 136., 129.],
        ...,
        [ 60.,  49.,  55., ...,  87.,  74.,  84.],
        [207., 212., 215., ..., 134., 139., 145.],
        [119., 119., 130., ..., 126., 124., 127.]], dtype=float32),
 array([[192., 175., 165., ..., 175., 166., 151.],
        [108., 105., 100., ..., 157., 149., 128.],
        [188., 195., 211., ..., 204., 208., 207.],
        ...,
        [197., 207., 209., ..., 219., 228., 223.],
        [ 90.,  87., 116., ..., 205., 212., 212.],
        [182., 198., 222., ..., 144., 156., 173.]], dtype=fl

In [113]:
np.vstack([train_folds_X[j] for j in range(num_folds) if j != 2])

array([[216., 227., 231., ..., 116.,  79.,  83.],
       [120., 119., 121., ..., 119., 118., 124.],
       [133., 163., 137., ..., 136., 166., 142.],
       ...,
       [ 95.,  99., 108., ..., 116., 121., 117.],
       [175., 179., 187., ...,  82.,  87.,  76.],
       [137., 139., 128., ..., 138., 143., 139.]], dtype=float32)

In [116]:
np.hstack([train_folds_y[j] for j in range(num_folds) if j != 2])

array([ True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False,  True, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False, False,  True, False, False,  True, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True,  True,  True, False,  True,  True,
       False, False, False,  True, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True, False,  True,  True, False,  True])

In [115]:
train_folds_y[1]

array([ True,  True, False,  True, False, False,  True, False, False,
        True, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False,  True])

In [124]:
train_X = train_X.reshape(train_X.shape[0], -1)
test_X = test_X.reshape(test_X.shape[0], -1)

knn_classifier = KNN(k=1)
knn_classifier.fit(train_X, train_y)

In [128]:
dists = knn_classifier.compute_distances_no_loops(test_X)

In [130]:
num_test = dists.shape[0]
pred = np.zeros(num_test, np.int)


In [133]:
neib = np.argsort(dists[5])[:3]

In [134]:
neib

array([284, 957, 909])

In [136]:
neibLabels = train_y[neib]


In [137]:
neibLabels

array([6, 3, 1], dtype=uint8)

In [139]:
unique, counts = np.unique(neibLabels, return_counts=True)

In [140]:
unique

array([1, 3, 6], dtype=uint8)

In [141]:
counts

array([1, 1, 1])

In [142]:
neibLabels.value_counts

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [144]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)

In [145]:
counts

array([0, 6, 4, 2])

In [147]:
from collections import Counter
a = [1,2,3,1,2,1,1,1,3,2,2,1]
b = Counter(a)
print(b.most_common(1))

[(1, 6)]


In [151]:
b

Counter({1: 6, 2: 4, 3: 2})

In [154]:
b.most_common(1)[0]

(1, 6)

In [5]:
k_nearest_labels = [1,1,2,2,3]

In [6]:
labels, counts = np.unique(k_nearest_labels, return_counts=True)

In [7]:
labels

array([1, 2, 3])

In [8]:
counts

array([2, 2, 1])

In [9]:
stat = dict(zip(labels, counts))

In [10]:
stat

{1: 2, 2: 2, 3: 1}

In [174]:
Counter(k_nearest_labels).most_common(1)[0]

(1, 2)

In [176]:
c = Counter(k_nearest_labels)

In [177]:
c

Counter({1: 2, 2: 2, 3: 1})

In [179]:
c.most_common(1)[0][0]

1

In [ ]:
stat

In [12]:
max(stat, key=stat.get)

1

In [4]:
import numpy as np

In [15]:
a = np.array([1,2,3,4,5])

In [19]:
np.exp(a)/np.exp(a).sum()

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

In [20]:
a = 5

In [21]:
len(a)

TypeError: object of type 'int' has no len()